/**
 * Centralized UI Strings for CampusBook
 * Following i18n/localization principles for easier wording & maintenance.
 */

export const UI_STRINGS = {
  common: {
    more_info: "Info Lebih Lanjut",
    book: "Pesan",
    available: "Tersedia",
    broken: "Perbaikan",
    capacity: "Kapasitas",
    building: "Gedung",
    floor: "Lantai",
    facilities: "Fasilitas",
    cancel: "Batal",
    back: "Kembali",
    submit: "Kirim",
    loading: "Memuat...",
    processing: "Memproses...",
    save: "Simpan",
    delete: "Hapus",
    edit: "Ubah",
    download: "Unduh",
    add: "Tambah",
    understand: "Sip, Mengerti",
    status: "Status",
  },
  rooms: {
    header_title: "Cari Ruangan",
    header_desc: "Temukan dan pesan ruangan untuk kegiatan Anda.",
    search_placeholder: "Cari nama atau gedung...",
    sort_name: "Nama (A-Z)",
    sort_location: "Lokasi",
    sort_cap_asc: "Kapasitas (Kecil-Besar)",
    sort_cap_desc: "Kapasitas (Besar-Kecil)",
    filter_min_cap: "Kapasitas Min.",
    filter_floor: "Lantai",
    filter_facility: "Fasilitas",
    not_found: "Tidak ada ruangan yang ditemukan.",
    detail_title: "Detail",
    rules_title: "Peraturan Ruangan",
    report_issue: "Laporkan Masalah",
    book_now: "Pesan Ruangan Ini",
    empty_facilities: "Tidak ada data fasilitas.",
  },
  booking: {
    my_bookings: "Pesanan Saya",
    my_bookings_desc: "Pantau status pemesanan ruangan Anda.",
    tab_active: "Pesanan Aktif",
    tab_history: "Riwayat Pesanan",
    empty_active: "Anda belum memiliki pesanan aktif.",
    empty_history: "Belum ada riwayat pesanan.",
    modal_title: "Pesan",
    reason_label: "Alasan Pemesanan",
    reason_placeholder: "Contoh: Kelas pengganti mata kuliah RPL...",
    select_date: "Pilih Tanggal",
    select_sks: "Jumlah SKS",
    select_slot: "Pilih Slot Waktu",
    checking_availability: "Memeriksa ketersediaan...",
    slot_available: "Slot tersedia untuk dipesan.",
    submit_request: "Ajukan Pesanan",
    cancel_booking: "Batalkan Pesanan",
    cancel_confirm_title: "Batalkan Pesanan?",
    cancel_confirm_desc: "Apakah Anda yakin ingin membatalkan pesanan ruangan ini? Tindakan ini tidak dapat diurungkan.",
    cancel_yes: "Ya, Batalkan",
    success_title: "Booking Berhasil!",
    success_desc: "Pesanan Anda telah diajukan dan sedang menunggu verifikasi admin.",
    proof_download: "Bukti Booking",
    proof_filename_prefix: "Bukti_Booking_",
    calendar: "Kalender",
    status_pending: "Menunggu Verifikasi",
    status_approved: "Disetujui",
    status_rejected: "Ditolak",
    status_cancelled: "Dibatalkan",
    status_completed: "Selesai",
  },
  dashboard: {
    welcome_mhs: "Halo, {name}! 👋",
    desc_mhs: "Selamat datang di Dasbor Mahasiswa. Di sini Anda dapat mencari ruangan, memesan fasilitas, dan memantau status pemesanan Anda.",
    welcome_dosen: "Selamat Datang, {name}!",
    desc_dosen: "Dasbor Dosen untuk pemesanan ruangan insidental, kelas pengganti, dan pelaporan fasilitas.",
    active_bookings: "Pesanan Aktif",
    empty_active: "Belum ada pesanan aktif.",
    recent_notifs: "Notifikasi Terbaru",
    empty_notifs: "Tidak ada notifikasi baru.",
    card_search_title: "Cari Ruangan",
    card_search_desc: "Cari dan pesan ruangan untuk kegiatan Anda.",
    card_bookings_title: "Pesanan Saya",
    card_bookings_desc: "Pantau status pemesanan dan unduh bukti booking.",
    card_report_title: "Lapor Masalah",
    card_report_desc: "Laporkan kendala teknis atau kerusakan fasilitas di ruangan.",
    card_dosen_search_desc: "Cari dan pesan ruangan untuk kelas pengganti atau kegiatan dosen.",
    card_dosen_bookings_title: "Status Booking",
    card_dosen_bookings_desc: "Pantau riwayat pemesanan dan unduh bukti booking digital.",
    card_dosen_report_title: "Laporan Kerusakan",
    card_dosen_report_desc: "Laporkan kendala teknis atau kerusakan fasilitas segera setelah penggunaan.",
  },
  profile: {
    incomplete_warning: "Profil Anda belum lengkap. Silakan lengkapi data diri di halaman Profil agar dapat mengajukan pemesanan.",
  }
};

export type UiStrings = typeof UI_STRINGS;
